# Generated by Django 4.2 on 2023-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.TextField(default="Bubby User"),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="blank_user.png", upload_to="profile_images"
            ),
        ),
    ]
