# Generated by Django 4.2 on 2023-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0003_profile_first_name_profile_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="Bubby User", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
